#!/usr/bin/env sh
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
# global settings
yabai -m config \
layout bsp \
window_origin_display focused \
split_ratio 0.50 \
split_type auto \
auto_balance on \
window_placement second_child \
window_shadow on \
window_gap 15 \
window_shadow on \
auto_balance on \
left_padding 15 \
top_padding 15 \
right_padding 15 \
bottom_padding 15 \
mouse_modifier fn \
mouse_drop_action swap \
mouse_action1 resize \
mouse_action2 move \
mouse_follows_focus off \
# yabai -m config \
# mouse_follows_focus off \
#    focus_follows_mouse          on             \
#    window_origin_display        focused        \
#    window_placement             second_child   \
#    window_topmost               on             \
#    window_shadow                off            \
#    window_animation_duration    0          \
#    window_opacity_duration      0          \
#    active_window_opacity        0            \
#    normal_window_opacity        0            \
#    window_opacity               off             \
#    insert_feedback_color        0xffd75f5f     \
#    active_window_border_color   0xff775759     \
#   normal_window_border_color   0xff555555     \
#    window_border_width          0              \
#    window_border_radius         22             \
#    window_border_blur           on             \
#    window_border_hidpi          on             \
#    window_border                off            \
#    split_ratio                  0.5           \
#    split_type                   auto           \
#    auto_balance                 on             \
    # top_padding                  15             \
    # bottom_padding               15             \
    # left_padding                 15             \
    # right_padding                15             \
    # window_gap                   15             \
    # layout                       bsp            \
    # mouse_modifier               fn             \
    # mouse_action1                move           \
    # mouse_action2                resize         \
    # mouse_drop_action            swap

echo "yabai configuration loaded.."
