general {
  output_format = "i3bar"
  colors = true
  color_good = "#00FF00"
  color_degraded = "#FFFF00"
  color_bad = "#FF0000"
}
#order += "ethernet eth0"
#order += "wireless wlan0"
#order += "wireless wlan1"
#order += "load"
order += "cpu_usage"
#order += "cpu_temperature 0"
#order += "disk /"
#order += "battery 0"
#order += "volume master"
#order += "time"

battery 0 {
  last_full_capacity = true
  # format = "%status %percentage"
  format = "%percentage"
  path = "/sys/class/power_supply/CMB0/uevent"
}

ethernet eth0 {
# if you use %speed, i3status requires root privileges
  format_up = " eth0   %quality  %essid   %bitrate  %ip"
  format_down = ""
}

wireless wlan0 {
  format_up = "wlan0   %quality  %essid   %bitrate  %ip"
  # format_down = "wlan0 "
  format_down = ""
}

wireless wlan1 {
  format_up = "wlan1  %quality  %essid   %bitrate  %ip"
  # format_down = "wlan1 "
  format_down = ""
}

time {
  format = " %a, %d %b %H:%M"
}

load {
  format = "%1min"
}

cpu_usage {
  format = "   %usage  "
}

cpu_temperature 0 {
  format = "%degrees °C"
  max_threshold = "65"
}

disk "/" {
  format = "  %free %avail"
}

volume master {
  format = " %volume"
  format_muted = " %volume"
  device = "default"
  mixer = "Master"
  mixer_idx = 0
}

